### PR TITLE
Update copy on Provider request confirmation page

### PR DESCRIPTION
**Pull request by jamestran201**
Trello: https://trello.com/c/tW8G5PiD/225-update-text-on-request-confirmation-page

Update copy on Provider request confirmation page according to the Trello card
Screenshot_2020-04-15 HospitalHero Healthcare workers need our help to fight COVID-19

### CODE REVIEW

**Review by cantino — APPROVED** [review]
Thanks @tmnhat2001!

**Comment by cantino** [comment]
I just invited you to the project. Feel free to join and merge this PR @tmnhat2001.

**Comment by jamestran201** [comment]
np, thanks! Can I merge the other approved PR's as well?

**Comment by cantino** [comment]
Yes, if they're approved, go for it!

**Pull request merged**
