### PR TITLE
Added hover states to buttons and links to meet accessibility guidelines

### PR DESCRIPTION
**Pull request by amysorto**
Changes based off mocks for buttons and links

### CODE REVIEW

**Review by cantino — APPROVED** [review]
Awesome @amysorto, thank you!

You have a pending invite to our GitHub organization. Did you get the email? You're welcome to accept the invite and then merge this.

**Comment by cwguan** [comment]
Hi Amy! I did some work for accessibility on the buttons that includes the hover state in a PR made on Friday and I think there's some duplicate/overlap work with the buttons (once mine gets merged in, all buttons globally should automatically styled correctly to meet accessibility)

just a heads up for potential conflicts in files like `Hero.jsx` and `SplitSection.jsx`

**Comment by amysorto** [comment]
Updated the pull request after fixing the merge conflicts and moving the styling to theme.js like in @cwguan 's pull request.

**Review by cwguan — APPROVED** [review]
LGTM! (:

**Review by cantino — APPROVED** [review]

**Pull request merged**
